### ISSUE TITLE
Error code 2

### ISSUE THREAD

**Issue by AomineD** [HMS-Core/hms-ads-demo-java#7]
I recent download this example code, and everytime return error code 2

**Comment by Mike-mei** [comment]
1. Make sure that your test phone is Huawei mobile
2. Please update HMS Core to the latest version
3. The error code 2 means that the ad request fails due to a network connection error. Please check whether the network connection is normal. More [error code](https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/error-code-0000001051073340)

**Comment by AomineD** [comment]
2.- HMS Core was in old version, **thanks for response!**
